lessons:
  outputs:
    dev:
      dataset: dbt_phin
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: robust-tracker-472000-g7
      threads: 60
      type: bigquery
  target: dev
